# Generated by Django 2.2.9 on 2020-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('photo', models.URLField(blank=True, verbose_name='照片網址')),
                ('location', models.CharField(max_length=100, verbose_name='地點')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
